version: "3.7"

services:
  db:
    image: postgres:12
    container_name: project-back_postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: project-back
    volumes:
      # - type: bind
      #   source: ./db-data
      #   target: /var/lib/postgres/data
      - ./db-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
