version: "3.7"

services:
  db:
    container_name: project-back_postgres
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: project_back, project_back_test
    volumes:
      - type: bind
        source: ./db-data
        target: /docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    container_name: project-back_redis
    image: redis:6
    ports:
      - "6379:6379"
